cron:
  image: fballiano/magento2-cron
  links:
    - db
    - redis
    - apache
    - varnish
  volumes:
    - ./magento2:/var/www/html
    - ./varnish.secret:/varnish.secret

varnish:
  image: fballiano/varnish
  ports:
    - "80:80"
    - "6082:6082"
  links:
    - apache
  volumes:
    - ./varnish.vcl:/etc/varnish/default.vcl
    - ./varnish.secret:/etc/varnish/secret
  environment:
    - CACHE_SIZE=256M

apache:
  image: fballiano/magento2-apache-php
#  ports:
#    - "8080:80"
  links:
    - db
    - redis
  volumes:
    - ./magento2:/var/www/html
    - ~/.composer/auth.json:/root/.composer/auth.json

db:
  image: mariadb:10.0
  ports:
    - "3306:3306"
  volumes_from:
    - dbdata
  environment:
    - MYSQL_ROOT_PASSWORD=magento2
    - MYSQL_DATABASE=magento2
    - MYSQL_USER=magento2
    - MYSQL_PASSWORD=magento2

dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql

redis:
  image: redis
